language: swift
osx_image: xcode9.1

cache:
    directories:
        - Carthage

before_script:
    - brew update
    - brew outdated carthage || brew upgrade carthage
    - carthage bootstrap --platform iOS --cache-builds --verbose

script:
    - set -o pipefail
    - xcodebuild -project UDF_Swift.xcodeproj -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
